### ISSUE TITLE
Do you really need ActionMailer?

### ISSUE THREAD

**Issue by fractaledmind** [virolea/panoptic#10]
My app failed to boot because I wasn't requiring ActionMailer for my app, and Panoptic requires it:
```
Unable to load application: NameError: uninitialized constant Panoptic::ActionMailer
Did you mean?  ActionCable
bundler: failed to load command: puma (.../shared/bundle/ruby/3.0.0/bin/puma)
.../shared/bundle/ruby/3.0.0/gems/panoptic-0.1.2/app/mailers/panoptic/application_mailer.rb:2:in `<module:Panoptic>': uninitialized constant Panoptic::ActionMailer (NameError)
Did you mean?  ActionCable
```

I did a code search, and I don't see the gem sending any emails. I'm presuming this is an artifact of the code generation.

**Comment by virolea** [comment]
You're right, no email is sent with the gem, this is the result of boilerplate code added during the engine initialization process. 

Removed it in https://github.com/virolea/panoptic/pull/12
