### ISSUE TITLE
Jobs should be sorted from newest to oldest

### ISSUE THREAD

**Issue by fractaledmind** [virolea/panoptic#13]
I'm on my phone on a train, so I can't make the simple PR, but jobs should be orders newest to oldest. When I come to the UI, I'm almost certainly interested in the most recent jobs.

**Comment by virolea** [comment]
I agree, it makes for the main jobs view. 

However, when it comes to scheduled and failed jobs, needs might be different: 
- scheduled jobs: In my case, I'd like to see the next job to be scheduled first, which corresponds to `scheduled_at: :asc` 
- failed jobs: I want to see the job that has been hanging in there the longest, which corresponds to first failed execution orderered by ascending creation 

What do you think about having those different ordering rules?

**Comment by fractaledmind** [comment]
I agree, makes sense. Maybe separate controllers for each tab to allow for separate logic?

**Comment by virolea** [comment]
Yes; there are already a `failed` and `scheduled` controllers so this will be easy
